//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeoFrontEnd.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKeywordService")]
    public interface IKeywordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetKeywordResults", ReplyAction="http://tempuri.org/IKeywordService/GetKeywordResultsResponse")]
        SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse GetKeywordResults(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetKeywordResults", ReplyAction="http://tempuri.org/IKeywordService/GetKeywordResultsResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse> GetKeywordResultsAsync(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeywordResults", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKeywordResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string searchTerm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string country;
        
        public GetKeywordResultsRequest() {
        }
        
        public GetKeywordResultsRequest(string lang, int num, string searchTerm, int start, string country) {
            this.lang = lang;
            this.num = num;
            this.searchTerm = searchTerm;
            this.start = start;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeywordResultsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKeywordResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetKeywordResultsResult;
        
        public GetKeywordResultsResponse() {
        }
        
        public GetKeywordResultsResponse(string[] GetKeywordResultsResult) {
            this.GetKeywordResultsResult = GetKeywordResultsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKeywordServiceChannel : SeoFrontEnd.ServiceReference1.IKeywordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeywordServiceClient : System.ServiceModel.ClientBase<SeoFrontEnd.ServiceReference1.IKeywordService>, SeoFrontEnd.ServiceReference1.IKeywordService {
        
        public KeywordServiceClient() {
        }
        
        public KeywordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeywordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse GetKeywordResults(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request) {
            return base.Channel.GetKeywordResults(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse> GetKeywordResultsAsync(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request) {
            return base.Channel.GetKeywordResultsAsync(request);
        }
    }
}
