//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeoFrontEnd.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordList", Namespace="http://schemas.datacontract.org/2004/07/SEOServices")]
    [System.SerializableAttribute()]
    public partial class KeywordList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] keywordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordsField, value) != true)) {
                    this.keywordsField = value;
                    this.RaisePropertyChanged("keywords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordStats", Namespace="http://schemas.datacontract.org/2004/07/SEOServices")]
    [System.SerializableAttribute()]
    public partial class KeywordStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeoFrontEnd.ServiceReference1.KeywordStat[] statsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeoFrontEnd.ServiceReference1.KeywordStat[] stats {
            get {
                return this.statsField;
            }
            set {
                if ((object.ReferenceEquals(this.statsField, value) != true)) {
                    this.statsField = value;
                    this.RaisePropertyChanged("stats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordStat", Namespace="http://schemas.datacontract.org/2004/07/SEOServices")]
    [System.SerializableAttribute()]
    public partial class KeywordStat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string keywordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string keyword {
            get {
                return this.keywordField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordField, value) != true)) {
                    this.keywordField = value;
                    this.RaisePropertyChanged("keyword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SEOServices")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int keywordlLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int urlLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeoFrontEnd.ServiceReference1.UrlKeywordSet[] urllKeywordSetsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int keywordlLimit {
            get {
                return this.keywordlLimitField;
            }
            set {
                if ((this.keywordlLimitField.Equals(value) != true)) {
                    this.keywordlLimitField = value;
                    this.RaisePropertyChanged("keywordlLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int urlLimit {
            get {
                return this.urlLimitField;
            }
            set {
                if ((this.urlLimitField.Equals(value) != true)) {
                    this.urlLimitField = value;
                    this.RaisePropertyChanged("urlLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeoFrontEnd.ServiceReference1.UrlKeywordSet[] urllKeywordSets {
            get {
                return this.urllKeywordSetsField;
            }
            set {
                if ((object.ReferenceEquals(this.urllKeywordSetsField, value) != true)) {
                    this.urllKeywordSetsField = value;
                    this.RaisePropertyChanged("urllKeywordSets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrlKeywordSet", Namespace="http://schemas.datacontract.org/2004/07/SEOServices")]
    [System.SerializableAttribute()]
    public partial class UrlKeywordSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] keywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordsField, value) != true)) {
                    this.keywordsField = value;
                    this.RaisePropertyChanged("keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteInfo", Namespace="http://schemas.datacontract.org/2004/07/SEOServices")]
    [System.SerializableAttribute()]
    public partial class WebsiteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] keywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] keywords {
            get {
                return this.keywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordsField, value) != true)) {
                    this.keywordsField = value;
                    this.RaisePropertyChanged("keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKeywordService")]
    public interface IKeywordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetKeywordResults", ReplyAction="http://tempuri.org/IKeywordService/GetKeywordResultsResponse")]
        SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse GetKeywordResults(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetKeywordResults", ReplyAction="http://tempuri.org/IKeywordService/GetKeywordResultsResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse> GetKeywordResultsAsync(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetAllKeywords", ReplyAction="http://tempuri.org/IKeywordService/GetAllKeywordsResponse")]
        SeoFrontEnd.ServiceReference1.GetAllKeywordsResponse GetAllKeywords(SeoFrontEnd.ServiceReference1.GetAllKeywordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetAllKeywords", ReplyAction="http://tempuri.org/IKeywordService/GetAllKeywordsResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetAllKeywordsResponse> GetAllKeywordsAsync(SeoFrontEnd.ServiceReference1.GetAllKeywordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/CrawlKeyword", ReplyAction="http://tempuri.org/IKeywordService/CrawlKeywordResponse")]
        SeoFrontEnd.ServiceReference1.CrawlKeywordResponse CrawlKeyword(SeoFrontEnd.ServiceReference1.CrawlKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/CrawlKeyword", ReplyAction="http://tempuri.org/IKeywordService/CrawlKeywordResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.CrawlKeywordResponse> CrawlKeywordAsync(SeoFrontEnd.ServiceReference1.CrawlKeywordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetKeywordStats", ReplyAction="http://tempuri.org/IKeywordService/GetKeywordStatsResponse")]
        SeoFrontEnd.ServiceReference1.GetKeywordStatsResponse GetKeywordStats(SeoFrontEnd.ServiceReference1.GetKeywordStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetKeywordStats", ReplyAction="http://tempuri.org/IKeywordService/GetKeywordStatsResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetKeywordStatsResponse> GetKeywordStatsAsync(SeoFrontEnd.ServiceReference1.GetKeywordStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetUserStats", ReplyAction="http://tempuri.org/IKeywordService/GetUserStatsResponse")]
        SeoFrontEnd.ServiceReference1.GetUserStatsResponse GetUserStats(SeoFrontEnd.ServiceReference1.GetUserStatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKeywordService/GetUserStats", ReplyAction="http://tempuri.org/IKeywordService/GetUserStatsResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetUserStatsResponse> GetUserStatsAsync(SeoFrontEnd.ServiceReference1.GetUserStatsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeywordResults", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKeywordResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int num;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string searchTerm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string country;
        
        public GetKeywordResultsRequest() {
        }
        
        public GetKeywordResultsRequest(string lang, int num, string searchTerm, int start, string country) {
            this.lang = lang;
            this.num = num;
            this.searchTerm = searchTerm;
            this.start = start;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeywordResultsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKeywordResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetKeywordResultsResult;
        
        public GetKeywordResultsResponse() {
        }
        
        public GetKeywordResultsResponse(string[] GetKeywordResultsResult) {
            this.GetKeywordResultsResult = GetKeywordResultsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllKeywords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllKeywordsRequest {
        
        public GetAllKeywordsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllKeywordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllKeywordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SeoFrontEnd.ServiceReference1.KeywordList GetAllKeywordsResult;
        
        public GetAllKeywordsResponse() {
        }
        
        public GetAllKeywordsResponse(SeoFrontEnd.ServiceReference1.KeywordList GetAllKeywordsResult) {
            this.GetAllKeywordsResult = GetAllKeywordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrawlKeyword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CrawlKeywordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string keyword;
        
        public CrawlKeywordRequest() {
        }
        
        public CrawlKeywordRequest(string keyword) {
            this.keyword = keyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrawlKeywordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CrawlKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CrawlKeywordResult;
        
        public CrawlKeywordResponse() {
        }
        
        public CrawlKeywordResponse(bool CrawlKeywordResult) {
            this.CrawlKeywordResult = CrawlKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeywordStats", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKeywordStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetKeywordStatsRequest() {
        }
        
        public GetKeywordStatsRequest(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeywordStatsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKeywordStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, SeoFrontEnd.ServiceReference1.KeywordStats> GetKeywordStatsResult;
        
        public GetKeywordStatsResponse() {
        }
        
        public GetKeywordStatsResponse(System.Collections.Generic.Dictionary<string, SeoFrontEnd.ServiceReference1.KeywordStats> GetKeywordStatsResult) {
            this.GetKeywordStatsResult = GetKeywordStatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserStats", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserStatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetUserStatsRequest() {
        }
        
        public GetUserStatsRequest(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserStatsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserStatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, SeoFrontEnd.ServiceReference1.KeywordStat[]>> GetUserStatsResult;
        
        public GetUserStatsResponse() {
        }
        
        public GetUserStatsResponse(System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, SeoFrontEnd.ServiceReference1.KeywordStat[]>> GetUserStatsResult) {
            this.GetUserStatsResult = GetUserStatsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKeywordServiceChannel : SeoFrontEnd.ServiceReference1.IKeywordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeywordServiceClient : System.ServiceModel.ClientBase<SeoFrontEnd.ServiceReference1.IKeywordService>, SeoFrontEnd.ServiceReference1.IKeywordService {
        
        public KeywordServiceClient() {
        }
        
        public KeywordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeywordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse GetKeywordResults(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request) {
            return base.Channel.GetKeywordResults(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetKeywordResultsResponse> GetKeywordResultsAsync(SeoFrontEnd.ServiceReference1.GetKeywordResultsRequest request) {
            return base.Channel.GetKeywordResultsAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.GetAllKeywordsResponse GetAllKeywords(SeoFrontEnd.ServiceReference1.GetAllKeywordsRequest request) {
            return base.Channel.GetAllKeywords(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetAllKeywordsResponse> GetAllKeywordsAsync(SeoFrontEnd.ServiceReference1.GetAllKeywordsRequest request) {
            return base.Channel.GetAllKeywordsAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.CrawlKeywordResponse CrawlKeyword(SeoFrontEnd.ServiceReference1.CrawlKeywordRequest request) {
            return base.Channel.CrawlKeyword(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.CrawlKeywordResponse> CrawlKeywordAsync(SeoFrontEnd.ServiceReference1.CrawlKeywordRequest request) {
            return base.Channel.CrawlKeywordAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.GetKeywordStatsResponse GetKeywordStats(SeoFrontEnd.ServiceReference1.GetKeywordStatsRequest request) {
            return base.Channel.GetKeywordStats(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetKeywordStatsResponse> GetKeywordStatsAsync(SeoFrontEnd.ServiceReference1.GetKeywordStatsRequest request) {
            return base.Channel.GetKeywordStatsAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.GetUserStatsResponse GetUserStats(SeoFrontEnd.ServiceReference1.GetUserStatsRequest request) {
            return base.Channel.GetUserStats(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetUserStatsResponse> GetUserStatsAsync(SeoFrontEnd.ServiceReference1.GetUserStatsRequest request) {
            return base.Channel.GetUserStatsAsync(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        SeoFrontEnd.ServiceReference1.AddUserResponse AddUser(SeoFrontEnd.ServiceReference1.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.AddUserResponse> AddUserAsync(SeoFrontEnd.ServiceReference1.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        SeoFrontEnd.ServiceReference1.UpdateUserResponse UpdateUser(SeoFrontEnd.ServiceReference1.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.UpdateUserResponse> UpdateUserAsync(SeoFrontEnd.ServiceReference1.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        SeoFrontEnd.ServiceReference1.GetUserResponse GetUser(SeoFrontEnd.ServiceReference1.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetUserResponse> GetUserAsync(SeoFrontEnd.ServiceReference1.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetWebsiteInfo", ReplyAction="http://tempuri.org/IUserService/GetWebsiteInfoResponse")]
        SeoFrontEnd.ServiceReference1.GetWebsiteInfoResponse GetWebsiteInfo(SeoFrontEnd.ServiceReference1.GetWebsiteInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetWebsiteInfo", ReplyAction="http://tempuri.org/IUserService/GetWebsiteInfoResponse")]
        System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetWebsiteInfoResponse> GetWebsiteInfoAsync(SeoFrontEnd.ServiceReference1.GetWebsiteInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SeoFrontEnd.ServiceReference1.User user;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(SeoFrontEnd.ServiceReference1.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddUserResult;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(bool AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SeoFrontEnd.ServiceReference1.User user;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(SeoFrontEnd.ServiceReference1.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateUserResult;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(bool UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SeoFrontEnd.ServiceReference1.User GetUserResult;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(SeoFrontEnd.ServiceReference1.User GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWebsiteInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWebsiteInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetWebsiteInfoRequest() {
        }
        
        public GetWebsiteInfoRequest(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWebsiteInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWebsiteInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SeoFrontEnd.ServiceReference1.WebsiteInfo GetWebsiteInfoResult;
        
        public GetWebsiteInfoResponse() {
        }
        
        public GetWebsiteInfoResponse(SeoFrontEnd.ServiceReference1.WebsiteInfo GetWebsiteInfoResult) {
            this.GetWebsiteInfoResult = GetWebsiteInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : SeoFrontEnd.ServiceReference1.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<SeoFrontEnd.ServiceReference1.IUserService>, SeoFrontEnd.ServiceReference1.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SeoFrontEnd.ServiceReference1.AddUserResponse AddUser(SeoFrontEnd.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.AddUserResponse> AddUserAsync(SeoFrontEnd.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.UpdateUserResponse UpdateUser(SeoFrontEnd.ServiceReference1.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.UpdateUserResponse> UpdateUserAsync(SeoFrontEnd.ServiceReference1.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.GetUserResponse GetUser(SeoFrontEnd.ServiceReference1.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetUserResponse> GetUserAsync(SeoFrontEnd.ServiceReference1.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public SeoFrontEnd.ServiceReference1.GetWebsiteInfoResponse GetWebsiteInfo(SeoFrontEnd.ServiceReference1.GetWebsiteInfoRequest request) {
            return base.Channel.GetWebsiteInfo(request);
        }
        
        public System.Threading.Tasks.Task<SeoFrontEnd.ServiceReference1.GetWebsiteInfoResponse> GetWebsiteInfoAsync(SeoFrontEnd.ServiceReference1.GetWebsiteInfoRequest request) {
            return base.Channel.GetWebsiteInfoAsync(request);
        }
    }
}
